= Diagrams

== Informatica / Kafka / Splunk

[plantuml, svg]
....
@startuml
!define iics_logo https://www.informatica.com/content/dam/informatica-com/en/images/gl01/informatica-logo.png
!define kafka_logo https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Apache_kafka_wordtype.svg/1024px-Apache_kafka_wordtype.svg.png
!define splunk_logo https://upload.wikimedia.org/wikipedia/commons/e/e8/Splunk-Logo.jpg
skinparam state {
	backgroundColor<<shared>> lightgreen
    BackgroundColor<<t>> tansparent
}

state main as "Main API" <<shared>> {
	state "Main processs" as iics {
      process: Main component created by developers
      process:  as part of the new system
      process: Contains SubProcesses for the project
      state proc1 as "SubProcess 1"
      state proc2 as "SubProcess 2"
      state procN as "SubProcess N"
      state throw as "Throw error"
      proc1 --> throw
      proc2 --> throw
      procN --> throw
    }
    
    state "<img:kafka_logo{scale=.2}>" as kafka <<t>>
    state "<img:splunk_logo{scale=.16}>" as splunk <<t>>
    throw --> kafka
    kafka -> splunk
    
}

main: Error handling wrapper
main: Process exposing main API	
proc1: Feature 1 implementation
proc2: Feature 2 implementation
procN: Feature N implementation
@enduml
....

== 

[plantuml, svg]
....
@startuml
skinparam state {
  BackgroundColor<<disabled>> lightgrey
  BackgroundColor<<t>> tansparent
}

!define iics_logo https://www.informatica.com/content/dam/informatica-com/en/images/gl01/informatica-logo.png
!define kafka_logo https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Apache_kafka_wordtype.svg/1024px-Apache_kafka_wordtype.svg.png
!define splunk_logo https://upload.wikimedia.org/wikipedia/commons/e/e8/Splunk-Logo.jpg

state "<img:iics_logo{scale=.8}>" as iics<<t>> {
    state "dev" as iics_dev
    state "uat" as iics_uat<<disabled>>
    state "prod" as iics_prod<<disabled>>
}

state "<img:kafka_logo{scale=.2}>" as kafka<<t>> {
    state "dev" as kafka_dev<<disabled>>
    state "uat" as kafka_uat
    state "prod" as kafka_prod
    kafka_dev: available only for \ninternal development
}

state "<img:splunk_logo{scale=.1}>" as splunk<<t>> {
    state "non-prod" as splunk_nonprod
    state "prod" as splunk_prod
}

iics_dev --> kafka_uat
iics_uat --> kafka_uat
iics_prod --> kafka_prod
kafka_uat --> splunk_nonprod
kafka_prod --> splunk_prod

@enduml
....
