= PlantUML examples
:data-uri:

== Sequence diagram
[plantuml, holiday_request, svg]
....
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
....




== State diagram
=== testdot

[plantuml, testdot, svg]
....
@startuml
testdot
@enduml
....

[plantuml, dummy, svg]
....
@startuml

[*] --> State1
State1 --> [*]
State1 : this is a string
State1 : this is another string

State1 -> State2
State2 --> [*]

@enduml
....

[plantuml, error_handling, svg]
....
@startuml
skinparam state {
    backgroundColor<<shared>> teal
}

state main as "Main API" {
main: process exposing general API

	state error as "General error handler" <<shared>> {
    	state wrapper as "Process wrapper" {
        	state Process1
            state Process2
            state Process3
            state raise as "Throw Error"
            Process1 --> raise
            Process2 --> raise
            Process3 --> raise
        }
    	
    }
    state log <<shared>>
    raise --> error
    error --> log
}

error: - Capture exceptions
error: - Log events
raise: Raise exception to General error handler
@enduml
....

=== Skinparams

Here's sample use of skinparams:

[plantuml, skin_param, svg]
....
@startuml
skinparam state {
  BackgroundColor<<disabled>> lightgrey
  BackgroundColor<<t>> tansparent
  BackgroundColor<<internal>> orange
}


!define iics_logo https://www.informatica.com/content/dam/informatica-com/en/images/gl01/informatica-logo.png
!define kafka_logo https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Apache_kafka_wordtype.svg/1024px-Apache_kafka_wordtype.svg.png
!define splunk_logo https://upload.wikimedia.org/wikipedia/commons/e/e8/Splunk-Logo.jpg


state "<img:iics_logo{scale=.8}>" as iics<<t>> {
    state "DEV CLE Service" as iics_dev
    state "UAT CLE Service" as iics_uat
    state "PROD CLE Service" as iics_prod
}


state "<img:kafka_logo{scale=.2}>" as kafka<<t>> {
    state "non-prod topic" as kafka_uat
    state "prod topic" as kafka_prod
    kafka_uat: common input topic \nfor all logging
    kafka_prod: common input topic \nfor all logging

    state "prod routing" as kafka_prod_router<<internal>>: Kafka internal routing \nbased on property
    state "uat routing" as kafka_uat_router<<internal>>: Kafka internal routing \nbased on property

    state "project1 prod topic" as kafka_prod_pr1
    state "project2 prod topic" as kafka_prod_pr2
    state "projectN prod topic" as kafka_prod_prN

    state "project1 uat topic" as kafka_uat_pr1
    state "project2 uat topic" as kafka_uat_pr2
    state "projectN uat topic" as kafka_uat_prN    
}


state "<img:splunk_logo{scale=.1}>" as splunk<<t>> {
    state "non-prod" as splunk_nonprod
    state "prod" as splunk_prod
    
    splunk_prod: - project1 index
    splunk_prod: - project2 index
    splunk_prod: - projectN index
    
    splunk_nonprod: - project1 index
    splunk_nonprod: - project2 index
    splunk_nonprod: - projectN index    
}


iics_dev --> kafka_uat
iics_uat --> kafka_uat
iics_prod --> kafka_prod
kafka_uat --> kafka_uat_router
kafka_prod --> kafka_prod_router
kafka_prod_router --> kafka_prod_pr1
kafka_prod_router --> kafka_prod_pr2
kafka_prod_router --> kafka_prod_prN
kafka_uat_router --> kafka_uat_pr1
kafka_uat_router --> kafka_uat_pr2
kafka_uat_router --> kafka_uat_prN
kafka_prod_pr1 --> splunk_prod
kafka_prod_pr2 --> splunk_prod
kafka_prod_prN --> splunk_prod
kafka_uat_pr1 --> splunk_nonprod
kafka_uat_pr2 --> splunk_nonprod
kafka_uat_prN --> splunk_nonprod

@enduml
....


back to link:adoc_starter/index.html[main Adoc starter] page.
back to link:index.html[main Adoc starter] page.
