# adoc_starter
:toc:
:stem:

## Assumptions
The scripts should be run in Windows Subsystem for Linux environment. For more information on how to enable wsl please refer https://docs.microsoft.com/en-us/windows/wsl/install-win10[this page]

## Setup script
`setup_adoc.sh` - to install all required components will install:

- asciidoctor - used to generate html output
- asciidoctor-diagram - used for diagrams
- asciidoctor-pdf - used to generate pdf output
- pandoc - used to generate docx

## Script to convert adoc to various formats
`docgen.sh` - this will use above mentioned tools to generate great looking documents in html/pdf/docx format.

### Syntax

`./docgen.sh <your_file.adoc> <desired_ouput [html/docx/pdf]>`

### Examples

To create HTML document, run:

`./docgen.sh test.adoc html` or just `./docgen.sh test.adoc` - in case of lack of value for format parameter a HTML will be generated by default

To create Word-compatible document, run:

`./docgen.sh test.adoc docx`

To create a document in PDF format, run:

`./docgen.sh test.adoc pdf`

### Math equations

Use 'stem' to generate Math equations (refer http://asciimath.org/[AsciiMath] for syntax)

stem:[sum_(i=1)^n i^3=((n(n+1))/2)^2]

## Sample adoc document
test.adoc - a sample file to play with.


## Docker environment

This folder also contains `Dockerfile` and `docker-compose.yml` with a basic setup and all libraries pre-installed. To run, simply execute `docker-compose run --rm adoc`
