ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= My document title

A normal paragraph.

IMPORTANT: The default *Asciidoctor* stylesheet automatically styles the first paragraph of the _preamble_ as a lead paragraph.

== Punkty numerowane

. dfdsg
. drugie
.. podpunkt
.. podpunkt
... _podpunkt_
... podpunkt
.. podpunkt
. trzecie
. tratatan

== Punkty bez numeracji:

* punkty
** punkty
** punkty
* _punkty_
* _punkty_
* punkty
* punkty

== rozdział pierwszy
Another normal paragraph.

NOTE: Diagrams are not rendered by Github (yet!...)

diagram naszej famili
[ditaa, rodzinka, svg]
....
+--------+          +--------+
|  TATA  +----+-----+  MAMA  |
+--------+    |     +--------+
              |
     +--------+---------+              
     |                  |
+----+---+          +---+------+
| Synek  |          | Córeczka |
+--------+          +----------+
....

[plantuml, rodzinka2, png]
....
@startuml
autonumber
Uczeń -> Przewodniczący: legimacja
note over Przewodniczący: zbiera wszystkie legitymacje
... Jak zebrane zostaną wszystkie legitymacje ...
Przewodniczący -> Sekretariat: Przynosi legitymacje \ndo podbicia
note over Sekretariat: podbija legitymacje
Sekretariat -> Przewodniczący: oddaje legitymacje
Przewodniczący -> Uczeń: rozdaje podbite legitymacje
@enduml
....



=== podrozdział z tabelką

[cols="5,5,1", options="header"]
|===
|Imię       |Nazwisko   |Punkty
|Piotr      |Iksiński   |5
|Wojtek     |Iksiński   |5
|Piotr      |Iksiński   |4
|Piotr      |Iksiński   |5
|===
