:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= AsciiDoc test document


A normal paragraph.
Note that a NewLine is ignored.

Until there is one blank line.

IMPORTANT: The default *Asciidoctor* stylesheet automatically styles the first paragraph of the _preamble_ as a lead paragraph.

== Numbered list

. first
. second
.. some lesser point
.. anoother lesser point
... even lesser point a
... even lesser point b
.. yet anoother lesser point
. third
. fourth

== Bullet list

* first
* second
** some lesser point
** anoother lesser point
*** even lesser point a
*** even lesser point b
** yet anoother lesser point
* third
* fourth

== Diagrams
Another normal paragraph.

NOTE: Diagrams are not rendered by Github (yet!...)

=== Family diagram
[ditaa, rodzinka, svg]
....
+--------+          +------+
|  DAD   +----+-----+  MUM |
+--------+    |     +------+
              |
     +--------+---------+              
     |                  |
 +---+-+          +-----+----+
 | Son |          | Daughter |
 +-----+          +----------+
....

== Sequence diagram
=== Getting approval for your holiday

[plantuml, holiday_request, svg]
....
@startuml
autonumber
You -> "Scrum Master" as SM: Ask for acceptance
SM -> You: Acknowledgement
note over SM: collect all holiday plans
... Once all holiday plans are placed in calendar ...
SM -> You: Approval
You -> "Line Manager" as LM: Notify
LM -> You: Approval
@enduml
....



== Table

[cols="5,5,1", options="header"]
|===
|First name    |Last name   |Points
|John          |Smith       |5
|David         |Smith       |5
|Mike          |Smith       |4
|Tyler         |Smith       |5
|===


== State diagram

[plantuml, testdot, svg]
....
@startuml
testdot
@enduml
....


[plantuml, error_handling, svg]
....
@startuml
skinparam state {
    backgroundColor<<shared>> teal
}

state main as "Main API" {
main: process exposing general API

	state error as "General error handler" <<shared>> {
    	state wrapper as "Process wrapper" {
        	state Process1
            state Process2
            state Process3
            state raise as "Throw Error"
            Process1 --> raise
            Process2 --> raise
            Process3 --> raise
        }
    	
    }
    state log <<shared>>
    raise --> error
    error --> log
}

error: - Capture exceptions
error: - Log events
raise: Raise exception to General error handler
@enduml
....
