name: asciidoctor-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    - name: asciidoctor-ghpages
      uses: MaciejGGH/asciidoctor-ghpages-action@03e679991bbb06d1a3349e44dce72c0f7b79c455
      with:
        # asciidoctor_params: --attribute=nofooter
        pdf_build: false
        # adoc_file_ext: .ascii # default is .adoc
        # source_dir: docs/ # default is .
        # slides_build: true
        # pre_build:
        # post_build:
